### PR TITLE
fix(defaults config): ensure that defaults are set by setting a promise

### PR DESCRIPTION
**Pull request by Jisay**
In TELECOM manager, first hit to at-internet is not triggered on page load because the promise to /me is not yet resolved (and so atInternetProvider.config.defaults is empty). We can use a promise to be sure that defaults are setted before sending the hit to at-internet.

### CODE REVIEW

**Comment by tremblaymath** [comment]
Before defaults are initialized, all hits are stocked in the queue and when the defaults are initialized(/me promise resolved) all hits of the queue are sent to At-internet.
You are not supposed to lose hits. 
Check your case with @whispyy

**Comment by Jisay** [comment]
Yes I am aware of this. The queue is send at next trackPage call. But the problem is that AT-Internet team can't know if a user only access to his manager and don't do anything on it. It works well on cloud manager but in telecom manager the first call to trackPage method is done before that /me call is done.

**Review by JeremyDec — APPROVED** [review]

**Comment by tremblaymath** [comment]
Effectively, a second call to trackpage should be done after /me resolve to send the queue.
We understand. 👍

**Comment by whispyy** [comment]
Good, thanks to have fixed this case. I'm gonna make a unit test for config as soon as possible to avoid case like this happening again.

**Review by whispyy — APPROVED** [review]

**Comment by Jisay** [comment]
Thx ! In fact, with this configuration, you have 2 choices :
- keep waiting that defaults are set like done in all managers ;
- or be sure the promise is resolved before sending any track page. In this configuration, the queue is not needed anymore - once the promise is resolved, the queue is not populated anymore. It stay there only for compatibility but should be removed in next major release.

**Comment by whispyy** [comment]
I've tested it out in cloud and telecom. It works.

**Pull request merged**
