### PR TITLE
refactor: update stack with component-rollup-config

### PR DESCRIPTION
**Pull request by antleblanc**
# Update stack

### 🗜 Refactor

987af8e — refactor: update stack with component-rollup-config

### 💥 Breaking Change

Module is now named as `ngAtInternet`

ref: ovh-ux/manager#201

### CODE REVIEW

**Comment by ovh-cds** [comment]
CDS Report build#18.0 ✘  
* build
  * build ✔ 
  * test ✘

**Comment by ovh-cds** [comment]
CDS Report build#19.0 ✘  
* build
  * build ✔ 
  * test ✘

**Comment by ovh-cds** [comment]
CDS Report build#20.0 ✘  
* build
  * build ✔ 
  * test ✘

**Comment by jleveugle** [comment]
Hello @antleblanc,
Your pull request is now closed due to inactivity.
Feel free to re-open it if you have any update.
Anna Bot for OVH UX <3

**Review by frenautvh — APPROVED** [review]

**Review by jleveugle — APPROVED** [review]

**Pull request merged**
